In [2]:
import pandas as pd

In [41]:
data = {
    "customer_type": ["member", "casual", "member"],
    "rideable_type": ["electric", "classic", "electric"],
    "avg_trip_duration_minutes": [2.3, 1.5, 3.4],
    "median_trip_duration_minutes": [1.2, 0.9, 1.7],
    "trip_count": [100, 100, 100],
    "active": [True, True, True],
    "trip_time": [2, 3, 5],
    "station_name": ["st_one", "st_two", "st_tree"],
    "station_role": ["start", "end", "start"],
    "s_trip_count": [100, 20, 100],
    "date": ["2024-01-01", "2024-01-01", "2024-01-02"],
    "hour": ["1", "2", "1"],
    "b_trip_count": [200, 100, 100],
    "year": ["2024", "2025", "2024"],
    "month": ["1", "2", "1"],
}

data_zero = {
    "customer_type": ["member", "casual", "member"],
    "rideable_type": ["electric", "classic", "electric"],
    "avg_trip_duration_minutes": [2.3, 1.5, 3.4],
    "median_trip_duration_minutes": [1.2, 0.9, 1.7],
    "trip_count": [0, 0, 0],
    "active": [True, True, True],
    "trip_time": [0, 0, 0],
    "station_name": ["st_one", "st_two", "st_tree"],
    "station_role": ["start", "end", "start"],
    "s_trip_count": [0, 0, 0],
    "date": ["2024-01-01", "2024-01-01", "2024-01-02"],
    "hour": ["1", "2", "1"],
    "b_trip_count": [0, 0, 0],
}

df_zero = pd.DataFrame(data_zero)
df = pd.DataFrame(data)
df

,customer_type,rideable_type,avg_trip_duration_minutes,median_trip_duration_minutes,trip_count,active,trip_time,station_name,station_role,s_trip_count,date,hour,b_trip_count,year,month
0,member,electric,2.3,1.2,100,True,2,st_one,start,100,2024-01-01,1,200,2024,1
1,casual,classic,1.5,0.9,100,True,3,st_two,end,20,2024-01-01,2,100,2025,2
2,member,electric,3.4,1.7,100,True,5,st_tree,start,100,2024-01-02,1,100,2024,1

In [23]:
ddd = pd.DataFrame(data)
ddd = ddd[["hour", "b_trip_count"]]
ddd = ddd.groupby("hour").sum()
ddd

      b_trip_count
hour
1              300
2              100

In [ ]:
ddd2 = pd.DataFrame(data)
ddd2 = ddd2.filter(["year", "month", "customer_type", "trip_count"])
display(ddd2)

ddd2 = ddd2.groupby(["year", "month", "customer_type"], as_index=False).sum(
    numeric_only=True
)
display(ddd2)

ddd3 = pd.DataFrame(data)
ddd3 = ddd3.filter(["year", "month", "customer_type", "trip_count"])
ddd3 = ddd3.groupby(["year", "month", "customer_type"], as_index=False).agg("sum")
ddd3["year_month"] = (
    ddd3["year"].astype(str) + "-" + ddd3["month"].astype(str).str.zfill(2)
)
ddd3 = ddd3.sort_values(["year", "month"], ascending=True)
display(ddd3)

   year month customer_type  trip_count
0  2024     1        member         100
1  2025     2        casual         100
2  2024     1        member         100

   year month customer_type  trip_count
0  2024     1        member         200
1  2025     2        casual         100

   year month customer_type  trip_count year_month
0  2024     1        member         200    2024-01
1  2025     2        casual         100    2025-02

In [44]:
dfm = pd.DataFrame(data)
dfm = dfm.filter(
    [
        "customer_type",
        "rideable_type",
        "avg_trip_duration_minutes",
        "median_trip_duration_minutes",
    ]
)
display(dfm)

dfm = dfm.melt(
    id_vars=["customer_type", "rideable_type"],
    value_vars=["avg_trip_duration_minutes", "median_trip_duration_minutes"],
    var_name="metric",
    value_name="value",
)
dfm = dfm.sort_values(["customer_type", "rideable_type"])
display(dfm)

,customer_type,rideable_type,avg_trip_duration_minutes,median_trip_duration_minutes
0,member,electric,2.3,1.2
1,casual,classic,1.5,0.9
2,member,electric,3.4,1.7

  customer_type rideable_type                        metric  value
1        casual       classic     avg_trip_duration_minutes    1.5
4        casual       classic  median_trip_duration_minutes    0.9
0        member      electric     avg_trip_duration_minutes    2.3
2        member      electric     avg_trip_duration_minutes    3.4
3        member      electric  median_trip_duration_minutes    1.2
5        member      electric  median_trip_duration_minutes    1.7

In [5]:
ddf = (
    df[df["station_role"] == "start"]
    .sort_values("s_trip_count", ascending=False)
    .iloc[0]["station_name"]
)

display(type(df[df["station_name"] == "start"]))
display(
    type(df[df["station_role"] == "start"].sort_values("s_trip_count", ascending=False))
)
display(
    type(
        df[df["station_role"] == "start"]
        .sort_values("s_trip_count", ascending=False)
        .iloc[0]
    )
)


ddf

pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

pandas.core.series.Series

'st_one'

In [6]:
bdf = df.groupby("hour", as_index=False)["b_trip_count"].sum()
display(type(bdf))
bdf = bdf.sort_values("b_trip_count", ascending=False)
display(type(bdf))
bdf

pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

  hour  b_trip_count
0    1           300
1    2           100

In [7]:
def get_kpis(dff) -> dict:
    trips: pd.DataFrame = dff

    total_trips = trips["trip_count"].sum()
    kpi_total_trips = total_trips

    aggregated = trips.groupby("customer_type")["trip_count"].sum()
    if total_trips == 0:
        member_pct = 0
        casual_pct = 0
    else:
        member_pct = (aggregated.get("member", 0) / total_trips * 100).round(2)
        casual_pct = (aggregated.get("casual", 0) / total_trips * 100).round(2)
    kpi_split_pct = f"{member_pct}/{casual_pct}"

    kpi_avg_time = float(trips["trip_time"].agg("mean").round(2))

    active_station = (
        trips[trips["station_role"] == "start"]
        .sort_values("s_trip_count", ascending=False)
        .iloc[0]
    )
    kpi_active_station = active_station["station_name"]

    hour_agg = trips.groupby("hour")["b_trip_count"].sum()
    kpi_busiest_hour = str(hour_agg.idxmax())

    return {
        "Total Trips": kpi_total_trips,
        "Member vs Casual split %": kpi_split_pct,
        "Avg Trip Duration": kpi_avg_time,
        "Most Active Station": kpi_active_station,
        "Busiest Hour": kpi_busiest_hour,
    }


display(get_kpis(df))
display(get_kpis(df_zero))

{'Total Trips': np.int64(300),
 'Member vs Casual split %': '66.67/33.33',
 'Avg Trip Duration': 3.33,
 'Most Active Station': 'st_one',
 'Busiest Hour': '1'}

{'Total Trips': np.int64(0),
 'Member vs Casual split %': '0/0',
 'Avg Trip Duration': 0.0,
 'Most Active Station': 'st_one',
 'Busiest Hour': '1'}